services:
  prometheus:
    image: prom/prometheus:latest
    container_name: mlops_hw8_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: mlops_hw8_grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/grafana.yaml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  postgres:
    image: postgres:16
    container_name: mlops_hw8_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  dqops:
    image: dqops/dqo:1.6.2
    container_name: mlops_hw8_dqops
    command: ["run", "--headless"]
    ports:
      - "8080:8888"
    volumes:
      - ./dqops_home:/dqo/userhome
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  grafana_data:
  postgres_data:
